namespace: micro-prod

backend:
  image: 352247465921.dkr.ecr.us-east-1.amazonaws.com/micro-backend
  tag: "5.0"
  imagePullPolicy: Always
  replicas: 1
  port: 8000
  env:
    ALLOWED_HOSTS: "https://abdd6374593494cb9bb8dd9ee99af2ce-2055544092.us-east-1.elb.amazonaws.com,myapp.local,localhost,127.0.0.1"

frontend:
  image: 352247465921.dkr.ecr.us-east-1.amazonaws.com/micro-frontend
  tag: "5.0"
  imagePullPolicy: Always
  replicas: 1
  port: 80

redis:
  image: redis
  tag: "7"
  port: 6379

database:
  type: rds
  host: micro-postgres.c6da8686exj5.us-east-1.rds.amazonaws.com
  port: "5432"
  name: appdb
  user: postgres
  password: strongpassword123!   

ingress:
  enabled: true
  className: alb
  scheme: internet-facing        
  targetType: ip
  certificateArn: arn:aws:acm:us-east-1:352247465921:certificate/b16c04b4-bfb7-4867-8d20-0907c2d41ddd
  host: myapp.example.com

